Introduce OAuth support with arbitrary providers (#133)
* feat(oauth): implementation of OAuth authentication for SEMP requests

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* feat(oauth): test setup with docker compose

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* refactor(oauth): separate HTTP configuration

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* feat(oauth): support for scopes

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* doc(oauth): explain testing directory, including non-functional refactoring

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* ci(oauth): check if OAuth flow is functioning in normal setup

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* chore: formatting

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* fix(oauth): missing env for testing

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* ci(oauth): fix linting error for parallel tests

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* ci(oauth): skip paralleltest linting for test methods which manipulate ENV variables

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* fix(oauth): linting issues, unnecessary conversions and newlines and error formatting

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* chore(oauth): tidying go.mod

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* ci(oauth): allow docker-compose e2e setup to take more time to ramp up

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* ci(oauth): unsupported timeout flag

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* ci(oauth): wait for compose services to come up

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* ci(oauth): pre-pull images

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* ci(oauth): missing test certificates

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* ci(oauth): check exited container

Signed-off-by: Torben Dury <torbendury@googlemail.com>

* chore: ignore documentational and E2E Test secrets, only used for testing purposes

Signed-off-by: Torben Dury <torbendury@googlemail.com>

---------

Signed-off-by: Torben Dury <torbendury@googlemail.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,11 +1,12 @@
+---
 name: Test
 
 on:
   push:
     branches:
-      - '*'
+      - "*"
   pull_request:
-    branches: [ master ]
+    branches: [master]
 
 jobs:
   lint-and-tidy:
@@ -42,3 +43,28 @@ jobs:
 
       - name: Run tests
         run: go test -v ./...
+  oauth_e2e_test:
+    name: OAuth E2E Test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v5
+      - name: Pre-pull docker images
+        run: |
+          docker compose -f oauth_test/docker-compose.yaml pull --ignore-buildable --ignore-pull-failures
+        timeout-minutes: 15
+      - name: Run docker compose
+        uses: hoverkraft-tech/compose-action@v2.3.0
+        with:
+          compose-file: oauth_test/docker-compose.yaml
+          up-flags: --wait --wait-timeout 600
+          compose-version: latest
+        timeout-minutes: 20
+      - name: Check metric scrape service status
+        run: |
+          status=$(docker compose -f oauth_test/docker-compose.yaml ps -aq check_metric_scrape | xargs docker inspect -f '{{.State.ExitCode}}')
+          if [ "$status" -eq 0 ]; then
+            echo "E2E test successful: check_metric_scrape exited with code 0."
+          else
+            echo "E2E test failed: check_metric_scrape exited with code $status."
+            exit 1
+          fi
